spring:
  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.nexuspm: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.transaction: WARN
    org.springframework.orm.jpa: WARN
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.type.descriptor.sql: WARN
